### ISSUE TITLE
Taginfo json file uses value=*

### ISSUE THREAD

**Issue by joto** [geometalab/osmaxx-docs#1]
The taginfo json file uses value=*, I suppose this means "any value", but in that case the value should just not be there at all. Currently this is interpreted as a literal asterisk character in the value.

**Comment by sfkeller** [comment]
Thanks, I'll have a look at it. That in fact should'nt be there (it actually probably comes from our original/internal YAML file).

**Comment by das-g** [comment]
In contrast to our [documentation for human consumption](https://github.com/geometalab/osmaxx/blob/c106869a50b20c64ec2d388fff7cf4d0a62bfc5a/docs/osmaxx_data_schema.md), we don't currently generate the taginfo project file JSON from the [schema YAML](https://github.com/geometalab/osmaxx/blob/c106869a50b20c64ec2d388fff7cf4d0a62bfc5a/docs/schema/osmaxx_schema.yaml) (although we plan to do that if we can find the time for it).

Thus I've simply manually edited the JSON file with #2.
