### ISSUE TITLE
Remove original svg

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-docs#13]
delete original svg (folder original) to only have one svgs.

**Comment by hixi** [comment]
Done, closing.

**Comment by geoSLG** [comment]
@hixi @das-g There are still two different directions to get to the original SVG's. Please merge the following pages:
https://github.com/geometalab/osmaxx-docs/tree/master/osmaxx-symbology/OSMaxx_point_symbols/svg
and
https://github.com/geometalab/osmaxx-docs/tree/master/osmaxx-symbology/original
Could you please upload the last version of SVG's as they are finished?

**Comment by das-g** [comment]
@geoSLG: on the `develop` branch, only [`osmaxx-symbology/OSMaxx_point_symbols/svg/`](https://github.com/geometalab/osmaxx-docs/tree/develop/osmaxx-symbology/OSMaxx_point_symbols/svg) remains of these. The [change that removed `osmaxx-symbology/original/`](https://github.com/geometalab/osmaxx-docs/commit/6598ac234593d286a0ad03d3c9496998a28072a4) has not been included in the `master` branch, yet. We'll marge this change (and other changes in `develop`) once the font is final. Until then, please refer to the [`develop` branch](https://github.com/geometalab/osmaxx-docs/tree/develop) to see the current state of TTF font and SVGs.

**Comment by das-g** [comment]
@sfkeller wrote in an Email:

> Am Mittwochabend 18. Mai wird das Datenschema - und diese Doku. - dann angepasst sein. Die zusätzlichen Tabellen werden dann auch in den ab dann getätigten Downloads enthalten sein.

So I was supposed to release the font (i.e. merge it to `master` branch) yesterday. Sorry that didn't happen.

@geoSLG, @cdeUG It's on the `master` branch, now, together with corresponding SVGs:
- SVGs: [on `master`](https://github.com/geometalab/osmaxx-docs/tree/master/osmaxx-symbology/OSMaxx_point_symbols/svg), [permalink to version 1.0.0](https://github.com/geometalab/osmaxx-docs/tree/symbolfont-1.0.0/osmaxx-symbology/OSMaxx_point_symbols/svg)
- TTF of the OSMaxx symbol font [on `master`](https://github.com/geometalab/osmaxx-docs/blob/master/osmaxx-symbology/OSMaxx_point_symbols/OSMaxx_v1.ttf?raw=true), [permalink to version 1.0.0](https://github.com/geometalab/osmaxx-docs/blob/symbolfont-1.0.0/osmaxx-symbology/OSMaxx_point_symbols/OSMaxx_v1.ttf?raw=true)

@hixi is working on linking it on the production webapp.

**Comment by cdeUG** [comment]
@das-g Thank you very much. Font is working well and all SVGs look now perfect to me!

@geoSLG : FYI
