### ISSUE TITLE
Roundup of to does for symbol font

### ISSUE THREAD

**Issue by cdeUG** [geometalab/osmaxx-docs#14]
1. Solution for display of all 151 symbols in new OSMaxx font on ArcGis (HSR, CDE, Geoservices)
2. Change name osmaxx.ttf into OSMaxx_v1.ttf (HSR)
3. Change actual "Default_OSMaxx_Maker" symbol with the new one sent on Friday 15/4/16, (HSR)
4. Symbol "special_industrial" to be center justified (HSR)
5. reduce dimension of symbol "public_library" slightly, actually it is bigger than the other character symbols 
6. Supply complete OSMaxx_v1.ttf on gemoetalab / osmaxx-docs
   @sfkeller @hixi @das-g @geoslg @geoBWM

**Comment by cdeUG** [comment]
Compare CDE OSMaxx1 Symbol Font of February 10 2016*\* to osmaxx.ttf.
Following differences are located at table column "Font embeddability":

![osmaxx_font_screen](https://cloud.githubusercontent.com/assets/18163172/14681470/863cca76-0721-11e6-86e8-1b0671ec433b.png)

On Windows Font viewer the symbol set of osmaxx.ttf is not displayed completely, as well.
![windows_fontviewer](https://cloud.githubusercontent.com/assets/18163172/14681652/53bb78ee-0722-11e6-8452-1498ca2e9bda.PNG)

Symbols up beyond unicode 128 are displayed in ArcGis with an default symbol, just at the moment when Unicode numbers of font subset "Latin-1 Supplement" starts and Subset "Basic Latin" ends.

**Comment by das-g** [comment]
> <span></span>1. Solution for display of all 151 symbols in new OSMaxx font on ArcGis (HSR, CDE, Geoservices)

Already tracked in #8

> <span></span>2. Change name osmaxx.ttf into OSMaxx_v1.ttf (HSR)

Already tracked in #12

> <span></span>3. Change actual "Default_OSMaxx_Maker" symbol with the new one sent on Friday 15/4/16, (HSR)

I didn't get that mail, I think. Please file a [separate issue](https://github.com/geometalab/osmaxx-docs/issues/new) for this and attach the symbol to that new issue. (Should be possible with drag&drop.)

> <span></span>4. Symbol "special_industrial" to be center justified (HSR)

Also already tracked in #8

> <span></span>5. reduce dimension of symbol "public_library" slightly, actually it is bigger than the other character symbols

This one is new. Let's track that here. (I'll change the issue title accordingly and will edit your initial comment on this issue.)

> <span></span>6. Supply complete OSMaxx_v1.ttf on gemoetalab / osmaxx-docs

That is implied with the other tasks. :-)

**Comment by das-g** [comment]
> > <span></span>5. reduce dimension of symbol "public_library" slightly, actually it is bigger than the other character symbols
> 
> This one is new. Let's track that here. (I'll change the issue title accordingly and will edit your initial comment on this issue.)

Actually, no, let's file a separate issue for this point, too, and close the issue here.

@cdeUG can you file separate issues for point 3 and point 5 of your list? Many thanks!

**Comment by das-g** [comment]
Actually-actually, let's track point 3 in the already existing #3. (Sorry, didn't remember we have that until just now.)

@cdeUG so only create a new issue for point 5 of your list, please.

**Comment by cdeUG** [comment]
Many thanks for distribution of tasks.
 @das-g Task 5 you could track on #8, it was once mentioned there..

**Comment by das-g** [comment]
> Task 5 you could track on #8, it was once mentioned there.

Oh, didn't see that.

So I'll just close this issue here.
