### ISSUE TITLE
Osmaxx_Data_Model_v3

### ISSUE THREAD

**Issue by geoBWM** [geometalab/osmaxx-docs#28]
It would be useful to remove any confusion as to which document is current - here a couple of minor issues whose resolution would remove a potential source of confusion.
- Header in the documentation needs updating: Osmaxx Data Model V.2
- Revision history: add current version and date

**Comment by sfkeller** [comment]
Ditta: Check if there are double entries of tags in the yaml (and later also the markdown and the .json)?
And pls. change:
- "hihgway" => "highway"  
- "Osmaxx" => "OSMaxx

**Comment by hixi** [comment]
Closing, will be solved and is partially solved already by other issues.
