### ISSUE TITLE
Some more editing needed on original SVGs

### ISSUE THREAD

**Issue by cdeUG** [geometalab/osmaxx-docs#31]
@das-g Some more editing needed on original colored SVGs as follows:
**color to be changed for**
- education_college into color RGB 200/70/20
- misc_comm_tower into color RGB 76/76/76
- public_post_office foreground RGB into color 200/70/20
- utility_plant backround into color RGB 0/0/0

**add background on**
health_clinic -> round disc RGB 255/255/255

**Change names for** 
- "public_building" into public_public_building
- red square “transport_bus_stop_and_railway_halt_alternative_M4_one.svg” into “transport_railway_halt_alternative_M4.svg”
- blue point “transport_bus_stop_and_railway_halt_alternative_M4_one.svg” into “transport_bus_stop_alternative_M4.svg”

**Comment by das-g** [comment]
> **Change names for**
> - [...]
> - blue point “transport_bus_stop_and_railway_halt_alternative_M4_**one**.svg” into “transport_bus_stop_alternative_M4.svg”

assuming that should be "transport_bus_stop_and_railway_halt_alternative_M4_**two**.svg" to "transport_bus_stop_alternative_M4.svg"

**Comment by cdeUG** [comment]
@das-g **Right for this** _"assuming that should be transport_bus_stop_and_railway_halt_alternative_M4_two.svg" to "transport_bus_stop_alternative_M4.svg"_

Sorry for copy-paste error!

**Comment by das-g** [comment]
fixed by bc22b83f4386809a70180992eb9ae39fac6f1108
