### ISSUE TITLE
Update Table documentation

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-docs#5]
Add missing and update existing tables in the `odt` tables documentation, especially:

First step: update missing
- [x] misc_l (was just missing from tocs)
- [x] address_p
- [x] utility_p (was just missing from tocs)
- [x] utility_a (was just missing from tocs)
- [x] route_l (was just missing from tocs)

Add new and changed one, once implemented (should be separate issue): 
- [ ] transport_l (new)
- [ ] coastline_l (new, issue)
- [ ] poi_a/poi_p: update (transport_l)
- [ ] misc_l
- [ ] address_p
- [ ] utility_p
- [ ] utility_a
- [ ] route_l
- [ ] coastline_l

**Comment by das-g** [comment]
> Add new and changed one, once implemented (should be separate issue): 
> - [ ] transport_l (new)
> - [ ] coastline_l (new, issue)
> - [ ] poi_a/poi_p: update (transport_l)
> - [ ] misc_l
> - [ ] address_p
> - [ ] utility_p
> - [ ] utility_a
> - [ ] route_l
> - [ ] coastline_l

This already _is_ a separate issue: #9

Closing #5. If anything is missing in #9, comment there or file a new issue.
