### ISSUE TITLE
Use Web Mercator as QGIS project projection

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-docs#74]
The current plan is to provide the QGIS symbology as a QGIS project file. A QGIS project has a projection used to display the data:
- _either_ the coordinate reference system (CRS) of the data itself
- _or_ a different CRS via **Project Properties** > **CRS** > **Enable 'on the fly' CRS transformation (OTF)**

Should the QGIS project file we'll include in the data download display the data in the data's spatial reference system or do an on-the-fly transformation to a fixed, display-suited coordinate system? (In either case, the user would be free to change that project setting by modifying the received project file using QGIS.)

**Comment by das-g** [comment]
Relevant snippets from the mail conversation concerning this topic:

> > > Google- und OSM-Standardkarten verwenden eine Mercator-Projektion/EPSG 3857. In den ArcGis verwende ich diese ebenfalls. Natürlich werden die Anwender die Projektion je nach Bedarf anpassen z.B. Wahl der UTM_Zone. WGS84/EPSG 4326  wirkt bei Frankfurt jetzt etwas verzogen, kann ja aber schnell geändert werden.
> > 
> > Falls (wie jetzt) "'on the fly' CRS transformation" nicht eingeschaltet ist, sieht der Benutzer die Karte im Referenzsystem der Daten (welches er ja inzwischen beim Bestellen des Exports auswählen kann). Bei WGS-84, das die Kugelkoordinaten einfach als planare kartesische Koordinaten re-interpretiert sieht das abseits vom Equator natürlich reichlich unproportional ("verzogen") aus, da die Längengrade gegenüber den Breitengraden gestreckt werden.
> > 
> > Sollten wir die "'on the fly' CRS transformation" einschalten und auf ein für die planare Anzeige geeignetes Koordinatensystem stellen, oder das dem Benutzer überlassen? Ich würde für letzteres plädieren.
> 
> Ich weiss, es gibt Argumente für beide Lösungen. Ich tendiere für erstere. Ich denke, die Benutzer wissen mit „on the fly“ umzugehen und können das CRS der Daten nach Bedarf anpassen oder auch nicht. Ich würde jedenfalls für die ArcGis-Vorlagen, die „on the fly“ Web-Mercator-Projektion gerne eingestellt lassen, damit bereits nach erstmaligem Einlesen der wie auch immer referenzierten Daten für praktisch jede geogr. Lage eine optisch einigermassen proportionale Karte erscheint. Angenommen, die Leute bestellen Daten z.B. im angebotenen CRS Pseudo-Merkator, dann müssen sie mit einem QGIS-Template in WGS84 die „on the fly CRS transformation“ ebenfalls aktivieren, oder nicht? Hinsichtlich Online-Publikation auf der OSMAXX-Seite möchte ich es natürlich euch überlassen, ob ihr für die ArcGis-Vorlagen die derzeitige Web-Mercator-Projektion in WGS84/EPSG 4326 transformieren möchtet. Ich denke, es wäre vielleicht sinnvoll, wenn auf der OSMaxx Seite an geeigneter Stelle darauf hingewiesen wird, wie es bezüglich Projektion in den QGIS- und ArcGis-Style-Templates gehandhabt wird.
> 
> > (Eine weitere Möglichkeit wäre, den Benutzer schon bei der Bestellung sowohl Daten- als auch Anzeige-Koordinatensystem wählen zu lassen. Ich glaube aber nicht, dass das den Implementations-Aufwand wert ist, noch dass das besonders benutzerfreundlich ist. Vermutlich würde das eher verwirren.)
> 
> Absolut einverstanden! Dass die Nutzer für die Daten zwischen fünf verschiedenen Koordinatensystemen auswählen können, erachte ich als einen Super-Service)

&nbsp;

> Da die Open Street Map Daten auf Basis des der Web Mercator Projektion erfasst worden sind, ist es am sinnvollsten auch diese zu verwenden. Die Nutzer können dies jedoch selbst entscheiden, ob sie dies möchten. Umprojizierungen sind immer auch mit Ungenauigkeiten verbunden, wenn also jemand seine GPS-Daten über OSMaxx umprojiziert legen will, kann es gut sein dass da bis zu einige Meter dazwischen sind. Ich würde sowohl die Wahl des Daten- als auch Anzeige-Koordinatensystems dem Nutzer überlassen. Oder wir bieten nur noch WGS 84 und Web Mercator an.

**Comment by das-g** [comment]
> Da die Open Street Map Daten auf Basis des der Web Mercator Projektion erfasst worden sind

AFAIK, the OpenStreetMap master data base, the OSM planet snapshot files (whether `*.osm.pbf` or `*.osm` XML) and diff files all have the coordinates in WGS-84 only (a.k.a. "GPS coordinates"). If they've been recorded or edited in an editor that displays them in Web Mercator (probably the case with any dedicated OSM editor) they've already been projected from WGS-84 to Web Mercator and back again. Same happens with GPS tracks displayed during editing. Except for round-off, these projections should be reversible, so there shouldn't be a huge loss of accuracy.

The way in which Web Mercator (pseudo-Mercator) is "inaccurate" is in how lengths and angles on-screen/on-paper don't really relate to on-the-ground lengths and angles. As the same "error" happens in reverse when projecting back, this doesn't matter as long as no metric measurements (as opposed to GPS tracks) are used to determine the coordinates. (Metric values in tag values don't matter, of course.)

So choosing freely what projection to display the data in only should introduce some more (hopefully insignificant) round-off error and thus be unproblematic.

@sfkeller correct me if I'm wrong on any point here.

**Comment by sfkeller** [comment]
Use Web Mercartor with OTF projection.
