### ISSUE TITLE
osmaxx.ttf

### ISSUE THREAD

**Issue by cdeUG** [geometalab/osmaxx-docs#8]
- [osmaxx.ttf](https://github.com/geometalab/osmaxx-docs/blob/master/osmaxx-symbology/OSMaxx_point_symbols/osmaxx.ttf) missing font symbols up to names character **t** (up to unicode 128) as follows: ![image003](https://cloud.githubusercontent.com/assets/97746/14598123/227848ac-0551-11e6-9147-22388bb55b84.jpg)
  - **transport**: bus_station,  bus_stop, railway_station, railway_halt, taxi_stand_helipad, ferry_station
  - **utility**: all
  - **water**: all
  - **worship**: all
- symbol **special_industrial** to be center justified (zentrieren)
- reduce dimension of symbol public_library slightly, actually it is bigger than the other character symbols of osmaxx.ttf

**Comment by hixi** [comment]
Most of this has been accidentally addressed in pull request #16 
Missing is only:
- [ ] symbol special_industrial to be center justified (zentrieren)
- [x] reduce dimension of symbol public_library slightly, actually it is bigger than the other character symbols of osmaxx.ttf

**Comment by cdeUG** [comment]
@hixi attached some information for new OSMaxx_v1.ttf
[osmaxx.pdf](https://github.com/geometalab/osmaxx-docs/files/254755/osmaxx.pdf)

**Comment by das-g** [comment]
> symbol special_industrial to be center justified (zentrieren)

[the icon currently on branch `develop`](https://github.com/geometalab/osmaxx-docs/blob/2ceb1b42465f1b5a8cd6c63098aefbeb10ca5cd4/osmaxx-symbology/OSMaxx_point_symbols/svg/special_industrial.svg) doesn't look insufficiently centered to me.

**Comment by cdeUG** [comment]
@das-g You are right. This task was referring to the older Font version **osmaxx.ttf** (see first comment on this issue).
With the recent **OSMaxx_v1 it is ok.**
