### ISSUE TITLE
Make same labels visible in QGIS symbology as in ArcGIS symbology (documentation) for same map scale

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-docs#80]
Some labels of layers `poi_a` and `poi_p` are currently missing:
![qgis_labels](https://cloud.githubusercontent.com/assets/97746/17130682/1a564b4e-531a-11e6-9fe3-4fab50527fdc.png)

corresponding area in ArcGIS:
![arcgis_labels](https://cloud.githubusercontent.com/assets/97746/17130714/3c517318-531a-11e6-8c41-ad8de4e989e5.png)

(Screenshots and markings by @cdeUG)

**Comment by sfkeller** [comment]
will be solved by #81
